wip
versity/scoutfs-tests pull request #12
Opened 2020-10-21 17:38 UTC by agrover

2020-10-29 21:04 UTC, zabbo commented on run-tests.sh
> +    -z <file> | Specify the filesystem's meta data device path that contains
-d and -z rubs me the wrong way.. maybe rename -D to -F for dumping ftrace on oops, and use -M for metadata and -D for data?  These single char options aren't looking like the best idea I've ever had.

2020-10-29 21:05 UTC, zabbo commented on run-tests.sh
> +msg "mounting $T_NR_MOUNTS mounts on $T_DATA_DEVICE"
Maybe print both devices here?

2020-10-29 21:05 UTC, zabbo commented on run-tests.sh
> +	test -b "$meta_dev" || die "failed to create temp device $data_dev"
meant to test data_dev..

2020-10-29 21:06 UTC, zabbo commented on run-tests.sh
> +	msg "mounting $data_dev on $dir"
print both again, probably?

2020-10-29 21:07 UTC, zabbo commented on run-tests.sh
> +	eval T_B$i=$data_dev
_DB to match _MB?

2020-10-29 21:09 UTC, zabbo commented on tests/setup-error-teardown.sh
> +echo "== interrupt waiting mount with minimal options"
Heh.  Might as well just remove everything after "waiting mount".

2020-10-29 21:11 UTC, zabbo requested changes
Definitely almost there, It's missing some mounts in funcs/fs.h, I guess the tests aren't all passing yet?

2020-11-05 19:40 UTC, agrover commented
tests that don't require two mounts (or are xfstests) are all passing.

2020-11-09 22:27 UTC, zabbo commented on tests/setup-error-teardown.sh
> +echo "== interrupt waiting mount"
The golden output needs to be updated for this.

2020-11-09 22:28 UTC, zabbo commented
> tests that don't require two mounts (or are xfstests) are all passing.

Nice!  And I think it'll be pretty easy to update xfstests.  It does mean that the single -e argument for the extra dev will want to turn into another pair of meta/data devices.  I'm not sure how best to work those into the options.. are single char options just a bad idea at this point?

2020-11-13 23:45 UTC, agrover commented
I used `-e` and `-f` (why? It's after e :smiley: ). This is only temporary. I think we want to move -tests to long options, which will make this a nonissue.

2020-11-19 19:46 UTC, zabbo commented
This was landed in another PR derived from this, with a few fixes added.

2020-11-19 19:46 UTC, closed without merging